### ISSUE TITLE
1.2.0 prerelease bug

### ISSUE THREAD

**Issue by jasikpark** [TauAkiou/amonguscapture-gtk#4]
While trying to run the prerelease I got this crash:

```
$ sudo ./AmongUsCapture-gtk-Linux-x64-Prerelease 
[sudo] password for calebjasik: 
/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease
/var/tmp/.net/root/AmongUsCapture-gtk-Linux-x64-Prerelease/mexn2vqi.u3f/AmongUsCapture.dll
/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/calebjasik/applications/aucapture-opener.desktop'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at AmongUsCapture.DBus.IPCadapterDBus.RegisterProtocol()
   at AmongUsCapture.DBus.IPCadapterDBus.HandleURIStart(String[] args)
   at AmongUsCapture.Program.Main(String[] args)
Aborted
```
whereas 1.1.0 works great: specifically only when run w/ sudo though.

**Comment by jasikpark** [comment]
I'm on Ubuntu 20.14 with regular steam among us, using the hosted version of automute.us

**Comment by jasikpark** [comment]
It looks like it's trying to access ~/applications/aucapture-opener.desktop when it actually installed that in ~/.local/share/applications/aucapture-opener.desktop????

**Comment by TauAkiou** [comment]
this is likely because sudo changes the local application data path (we access this in code by using Environment.SpecialFolder.LocalApplicationData) so it will fail, because it doesn't exist. Likely a problem with running it through sudo.

**Comment by jasikpark** [comment]
Output for dmesg while running the prerelease

```
[ 2779.855462] __report_access: 25300 callbacks suppressed
[ 2779.855464] ptrace attach of "Z:\x5chome\x5ccalebjasik\x5c.steam\x5cdebian-installation\x5csteamapps\x5ccommon\x5cAmong Us\x5cAmong Us.exe"[5885] was attempted by "/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease aucapture://discord.automute.us:8123/4FDACBD3"[8558]
[ 2779.856216] ptrace attach of "Z:\x5chome\x5ccalebjasik\x5c.steam\x5cdebian-installation\x5csteamapps\x5ccommon\x5cAmong Us\x5cAmong Us.exe"[5885] was attempted by "/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease aucapture://discord.automute.us:8123/4FDACBD3"[8558]
[ 2779.856231] ptrace attach of "Z:\x5chome\x5ccalebjasik\x5c.steam\x5cdebian-installation\x5csteamapps\x5ccommon\x5cAmong Us\x5cAmong Us.exe"[5885] was attempted by "/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease aucapture://discord.automute.us:8123/4FDACBD3"[8558]
[ 2779.857844] ptrace attach of "Z:\x5chome\x5ccalebjasik\x5c.steam\x5cdebian-installation\x5csteamapps\x5ccommon\x5cAmong Us\x5cAmong Us.exe"[5885] was attempted by "/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease aucapture://discord.automute.us:8123/4FDACBD3"[8558]
[ 2779.858620] ptrace attach of "Z:\x5chome\x5ccalebjasik\x5c.steam\x5cdebian-installation\x5csteamapps\x5ccommon\x5cAmong Us\x5cAmong Us.exe"[5885] was attempted by "/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease aucapture://discord.automute.us:8123/4FDACBD3"[8558]
[ 2779.858659] ptrace attach of "Z:\x5chome\x5ccalebjasik\x5c.steam\x5cdebian-installation\x5csteamapps\x5ccommon\x5cAmong Us\x5cAmong Us.exe"[5885] was attempted by "/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease aucapture://discord.automute.us:8123/4FDACBD3"[8558]
[ 2779.859120] ptrace attach of "Z:\x5chome\x5ccalebjasik\x5c.steam\x5cdebian-installation\x5csteamapps\x5ccommon\x5cAmong Us\x5cAmong Us.exe"[5885] was attempted by "/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease aucapture://discord.automute.us:8123/4FDACBD3"[8558]
[ 2779.859133] ptrace attach of "Z:\x5chome\x5ccalebjasik\x5c.steam\x5cdebian-installation\x5csteamapps\x5ccommon\x5cAmong Us\x5cAmong Us.exe"[5885] was attempted by "/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease aucapture://discord.automute.us:8123/4FDACBD3"[8558]
[ 2779.859143] ptrace attach of "Z:\x5chome\x5ccalebjasik\x5c.steam\x5cdebian-installation\x5csteamapps\x5ccommon\x5cAmong Us\x5cAmong Us.exe"[5885] was attempted by "/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease aucapture://discord.automute.us:8123/4FDACBD3"[8558]
[ 2779.859155] ptrace attach of "Z:\x5chome\x5ccalebjasik\x5c.steam\x5cdebian-installation\x5csteamapps\x5ccommon\x5cAmong Us\x5cAmong Us.exe"[5885] was attempted by "/home/calebjasik/AmongUsCapture-gtk-Linux-x64-Prerelease aucapture://discord.automute.us:8123/4FDACBD3"[8558]
```

**Comment by TauAkiou** [comment]
Related to Issue #3 - closing
